---
n_epoch:          20000
batch_size:       64
patience:         200
# === change together ===
split:            'scaffold'        # random/scaffold
mode:             'regression'    # regression/classification/soft
model_dir:        '../SavedModel/DeepChemPermeability/'
csv_dir:          './CSV/Predictions/'
