---
n_epoch:          2
batch_size:       64
patience:         200
# === change together ===
split:            'soft'        # random/scaffold
mode:             'classification'    # regression/classification/soft
model_dir:        '../../SavedModel/DeepChemPermeability/'
csv_dir:          '../CSV/Predictions/'
