---
n_epoch:          2000
batch_size:       64
patience:         20
# === change together ===
split:            'scaffold'        # random/scaffold
mode:             'classification'    # regression/classification/soft
model_dir:        '../SavedModel/BenchmarkCycPeptMP/'
csv_dir:          './CSV/Predictions/'
model:            'PAGTN'
repeat:           10
